package vista;

import java.awt.Dimension;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modelo.eEstadoSolicitud;
import modelo.eLogin;
import modelo.eSolicitud;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author CesarMatias
 */
public class frmLIstadoSolicitud extends javax.swing.JFrame implements DocumentListener {

    DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
    DateFormat datePy = new SimpleDateFormat("dd/MM/YYYY");
    eEstadoSolicitud mEst;
    eSolicitud mod;

    public frmLIstadoSolicitud() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Listado de Solicitudues");
        setSize(new Dimension(500, 180));

        // campos ocultos
        txtCodigo.setVisible(false);
        txtFecIni.setVisible(false);
        txtFecFin.setVisible(false);
        cboEstado.setVisible(false);
        lblCodigo.setVisible(false);
        lblEstado.setVisible(false);
        lblFecIni.setVisible(false);
        lblFechFin.setVisible(false);

        btnImprimir.setEnabled(false);

        txtCodigo.getDocument().addDocumentListener(this);
        ((JTextField) txtFecIni.getDateEditor().getUiComponent()).getDocument().addDocumentListener(this);
        ((JTextField) txtFecFin.getDateEditor().getUiComponent()).getDocument().addDocumentListener(this);

//        icono de la aplicacion
        java.net.URL imageURL = frmPrincipal.class.getResource("/img/icono.png");
        ImageIcon icono = new ImageIcon(imageURL);
        Image im = icono.getImage();
        setIconImage(im);

        this.mEst = new eEstadoSolicitud(); // modelo de estado
        this.mod = new eSolicitud();
        mEst.carCombo(cboEstado);

        rCodigo.setSelected(true);
        habilitarcampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rCodigo = new javax.swing.JRadioButton();
        rEstado = new javax.swing.JRadioButton();
        rFecha = new javax.swing.JRadioButton();
        rTodo = new javax.swing.JRadioButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblFecIni = new javax.swing.JLabel();
        txtFecIni = new com.toedter.calendar.JDateChooser();
        lblFechFin = new javax.swing.JLabel();
        txtFecFin = new com.toedter.calendar.JDateChooser();
        lblEstado = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Selcciona el tipo de Filtro:");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        grupo.add(rCodigo);
        rCodigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rCodigo.setText("Codigo");
        rCodigo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rCodigoItemStateChanged(evt);
            }
        });
        jPanel2.add(rCodigo);

        grupo.add(rEstado);
        rEstado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rEstado.setText("Estado");
        rEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rEstadoItemStateChanged(evt);
            }
        });
        jPanel2.add(rEstado);

        grupo.add(rFecha);
        rFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rFecha.setText("Fecha");
        rFecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rFechaItemStateChanged(evt);
            }
        });
        jPanel2.add(rFecha);

        grupo.add(rTodo);
        rTodo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        rTodo.setText("Todo");
        rTodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rTodoItemStateChanged(evt);
            }
        });
        jPanel2.add(rTodo);

        lblCodigo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblCodigo.setText("Codigo");

        txtCodigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblFecIni.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblFecIni.setText("Fecha Inicio");

        txtFecIni.setDateFormatString("dd-MM-yyyy");
        txtFecIni.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtFecIniPropertyChange(evt);
            }
        });

        lblFechFin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblFechFin.setText("Fecha Fin");

        txtFecFin.setDateFormatString("dd-MM-yyyy");

        lblEstado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblEstado.setText("Estado");

        cboEstado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cboEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboEstadoItemStateChanged(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMensaje.setText(".");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimir);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minus.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblFecIni)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFechFin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblFechFin)
                    .addComponent(lblFecIni)
                    .addComponent(txtFecIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstado))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMensaje))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiardatos();
        rCodigo.setSelected(true);
        btnImprimir.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        String codigo = "", estado = "", fecha = "", where = "1";

        if (rCodigo.isSelected()) {
            codigo = txtCodigo.getText().trim();
            where += " AND s.solnro = " + codigo;
        }

        if (rEstado.isSelected()) {
        
            estado = cboEstado.getSelectedItem().toString();
            where += " AND e.escodigo = " + cboEstado.getItemAt(cboEstado.getSelectedIndex()).getCodigo();
            ;
        }

        if (rFecha.isSelected()) {
            fecha = "Desde " + datePy.format(txtFecIni.getDate()) + " Hasta " + datePy.format(txtFecFin.getDate());
            where += " AND s.solfecha BETWEEN '" + dateFormat.format(txtFecIni.getDate()) + "' AND '" + dateFormat.format(txtFecFin.getDate()) + "'";
        }

        try {
            HashMap param = new HashMap();
            param.put("P_WHERE", where);
            param.put("P_USER", eLogin.Alias);
            param.put("P_CODIGO", codigo);
            param.put("P_ESTADO", estado);
            param.put("P_FECHA", fecha);
            JasperPrint jp = JasperFillManager.fillReport("src/reporte/rptListadoSolicitudes.jasper", param, this.mod.cone());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cboEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboEstadoItemStateChanged
        if (rCodigo.isSelected()) {
            if (txtCodigo.getText().trim().isEmpty() || !txtCodigo.getText().trim().matches("^[1-9][0-9]*")) {
                lblMensaje.setText("Codigo no puede estar nulo, debe ser solo número no puede empezar con 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rEstado.isSelected()) {
            if (cboEstado.getSelectedItem().toString().equals("0 - Seleccione...")) {
                lblMensaje.setText("Estado no puede ser 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rFecha.isSelected()) {
            if (txtFecIni.getDate() == null || txtFecFin.getDate() == null) {
                lblMensaje.setText("Fecha Inicio y Fecha Fin no puden estar nulos");
                btnImprimir.setEnabled(false);
            } else if (txtFecIni.getDate().after(txtFecFin.getDate())) {
                lblMensaje.setText("Fecha Inicio <= Fecha Fin");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }
    }//GEN-LAST:event_cboEstadoItemStateChanged

    private void txtFecIniPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtFecIniPropertyChange
        if (txtFecIni.getDate() != null) {
            txtFecFin.setMinSelectableDate(txtFecIni.getDate());
        }
    }//GEN-LAST:event_txtFecIniPropertyChange

    private void rCodigoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rCodigoItemStateChanged
        habilitarcampos();
    }//GEN-LAST:event_rCodigoItemStateChanged

    private void rEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rEstadoItemStateChanged
        habilitarcampos();
    }//GEN-LAST:event_rEstadoItemStateChanged

    private void rFechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rFechaItemStateChanged
        habilitarcampos();
    }//GEN-LAST:event_rFechaItemStateChanged

    private void rTodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rTodoItemStateChanged
        habilitarcampos();
    }//GEN-LAST:event_rTodoItemStateChanged

    private void limpiardatos() {
        txtCodigo.setText(null);
        txtFecIni.setDate(null);
        txtFecFin.setDate(null);
        cboEstado.setSelectedIndex(0);
    }

    private void habilitarcampos() {
        if (rCodigo.isSelected()) {
            lblCodigo.setVisible(true);
            txtCodigo.setVisible(true);
            txtCodigo.grabFocus();

            lblFecIni.setVisible(false);
            txtFecIni.setVisible(false);
            lblFechFin.setVisible(false);
            txtFecFin.setVisible(false);
            lblEstado.setVisible(false);
            cboEstado.setVisible(false);
        }

        if (rEstado.isSelected()) {
            lblEstado.setVisible(true);
            cboEstado.setVisible(true);
            cboEstado.grabFocus();

            lblFecIni.setVisible(false);
            txtFecIni.setVisible(false);
            lblFechFin.setVisible(false);
            txtFecFin.setVisible(false);
            lblCodigo.setVisible(false);
            txtCodigo.setVisible(false);
        }

        if (rFecha.isSelected()) {
            lblFecIni.setVisible(true);
            txtFecIni.setVisible(true);
            lblFechFin.setVisible(true);
            txtFecFin.setVisible(true);
            txtFecIni.grabFocus();

            lblEstado.setVisible(false);
            cboEstado.setVisible(false);
            lblCodigo.setVisible(false);
            txtCodigo.setVisible(false);
        }

        if (rTodo.isSelected()) {
            lblEstado.setVisible(false);
            cboEstado.setVisible(false);
            lblFecIni.setVisible(false);
            txtFecIni.setVisible(false);
            lblFechFin.setVisible(false);
            txtFecFin.setVisible(false);
            lblCodigo.setVisible(false);
            txtCodigo.setVisible(false);
            btnImprimir.setEnabled(true);
        }
        limpiardatos();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLIstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLIstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLIstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLIstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLIstadoSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<eEstadoSolicitud> cboEstado;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecIni;
    private javax.swing.JLabel lblFechFin;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JRadioButton rCodigo;
    private javax.swing.JRadioButton rEstado;
    private javax.swing.JRadioButton rFecha;
    private javax.swing.JRadioButton rTodo;
    public javax.swing.JTextField txtCodigo;
    public com.toedter.calendar.JDateChooser txtFecFin;
    public com.toedter.calendar.JDateChooser txtFecIni;
    // End of variables declaration//GEN-END:variables

    @Override
    public void insertUpdate(DocumentEvent e) {
        if (rCodigo.isSelected()) {
            if (txtCodigo.getText().trim().isEmpty() || !txtCodigo.getText().trim().matches("^[1-9][0-9]*")) {
                lblMensaje.setText("Codigo no puede estar nulo, debe ser solo número no puede empezar con 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rEstado.isSelected()) {
            if (cboEstado.getSelectedItem().toString().equals("0 - Seleccione...")) {
                lblMensaje.setText("Estado no puede ser 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rFecha.isSelected()) {
            if (txtFecIni.getDate() == null || txtFecFin.getDate() == null) {
                lblMensaje.setText("Fecha Inicio y Fecha Fin no puden estar nulos");
                btnImprimir.setEnabled(false);
            } else if (txtFecIni.getDate().after(txtFecFin.getDate())) {
                lblMensaje.setText("Fecha Inicio <= Fecha Fin");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        if (rCodigo.isSelected()) {
            if (txtCodigo.getText().trim().isEmpty() || !txtCodigo.getText().trim().matches("^[1-9][0-9]*")) {
                lblMensaje.setText("Codigo no puede estar nulo, debe ser solo número no puede empezar con 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rEstado.isSelected()) {
            if (cboEstado.getSelectedItem().toString().equals("0 - Seleccione...")) {
                lblMensaje.setText("Estado no puede ser 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rFecha.isSelected()) {
            if (txtFecIni.getDate() == null || txtFecFin.getDate() == null) {
                lblMensaje.setText("Fecha Inicio y Fecha Fin no puden estar nulos");
                btnImprimir.setEnabled(false);
            } else if (txtFecIni.getDate().after(txtFecFin.getDate())) {
                lblMensaje.setText("Fecha Inicio <= Fecha Fin");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        if (rCodigo.isSelected()) {
            if (txtCodigo.getText().trim().isEmpty() || !txtCodigo.getText().trim().matches("^[1-9][0-9]*")) {
                lblMensaje.setText("Codigo no puede estar nulo, debe ser solo número no puede empezar con 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rEstado.isSelected()) {
            if (cboEstado.getSelectedItem().toString().equals("0 - Seleccione...")) {
                lblMensaje.setText("Estado no puede ser 0");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }

        if (rFecha.isSelected()) {
            if (txtFecIni.getDate() == null || txtFecFin.getDate() == null) {
                lblMensaje.setText("Fecha Inicio y Fecha Fin no puden estar nulos");
                btnImprimir.setEnabled(false);
            } else if (txtFecIni.getDate().after(txtFecFin.getDate())) {
                lblMensaje.setText("Fecha Inicio <= Fecha Fin");
                btnImprimir.setEnabled(false);
            } else {
                lblMensaje.setText(null);
                btnImprimir.setEnabled(true);
            }
        }
    }
}
